apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: auto-provider-id
build:
  artifacts:
    - image: pfenerty/auto-provider-id
      kaniko:
        dockerfile: Dockerfile
      # docker:
      #   dockerfile: Dockerfile
  cluster:
    dockerConfig:
      secretName: docker-hub-creds
    namespace: skaffold-builds
    tolerations:
    - key: "node.cloudprovider.kubernetes.io/uninitialized"
      operator: "Equal"
      value: "true"
      effect: "NoSchedule"
manifests:
  rawYaml:
    - deploy/*.yaml
