name: Image Build
on: [push]
jobs:
  build_image:
    name: Build Image
    runs-on: ubuntu-latest
    container:
        image: gcr.io/kaniko-project/executor:debug
    steps:
        - name: Build the image
          id: build_image
          run: |
            mkdir -p /kaniko/.docker
            echo "{\"auths\":{\"ghcr.io\":{\"username\":\"${{ github.actor }}\",\"password\":\"${{ secrets.CI_TOKEN }}\"}}}" > /kaniko/.docker/config.json
            /kaniko/executor \
              --destination=ghcr.io/${{ github.actor }}/auto-provider-id \
              --context=git://${{ secrets.CI_TOKEN }}@github.com/${{ github.repository}}#${{ github.ref }}#${{ github.sha }} \
              --image-name-with-digest-file image-ref.txt
            echo "build_image_ref=$(cat image-ref.txt)" >> "$GITHUB_OUTPUT"
    outputs:
      built_image_ref: ${{ steps.build_image.outputs.build_image_ref }}
  scan_image:
    name: CVE Scan
    runs-on: ubuntu-latest
    needs: build_image
    steps: 
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@7b7aa264d83dc58691451798b4d117d53d21edfe
        with:
          image-ref: ${{ needs.build_image.outputs.built_image_ref }}
          format: 'template'
          template: '@/contrib/sarif.tpl'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'