name: Image Build
on: [push]
jobs:
  build_image:
    name: Build Image
    runs-on: ubuntu-latest
    container:
        image: gcr.io/kaniko-project/executor:debug
    steps:
        - name: Build the image
          run: |
            mkdir -p /kaniko/.docker
            echo "{\"auths\":{\"gchr.io\":{\"username\":\"${{ github.actor }}\",\"password\":\"${{ secrets.GITHUB_TOKEN }}\"}}}" > /kaniko/.docker/config.json
            echo "https://${{secrets.GITHUB_TOKEN}}@github.com/${{ github.repository}}#${{ github.ref }}#${{ github.sha }}"
            /kaniko/executor --destination  gchr.io/${{ github.actor }}/auto-provider-id --context=https://${{secrets.GITHUB_TOKEN}}@github.com/${{ github.repository}}#${{ github.ref }}#${{ github.sha }}