name: Image Build
on: [push]
jobs:
  build_image:
    name: Build Image
    runs-on: ubuntu-latest
    container:
        image: gcr.io/kaniko-project/executor:debug
    steps:
        - name: Build the image
          run: |
            mkdir -p /kaniko/.docker
            echo "{\"auths\":{\"gchr.io\":{\"username\":\"${{ github.actor }}\",\"password\":\"${{ secrets.CI_TOKEN }}\"}}}" > /kaniko/.docker/config.json
            /kaniko/executor --destination=ghcr.io/${{ github.actor }}/auto-provider-id --context=git://${{ secrets.CI_TOKEN }}@github.com/${{ github.repository}}#${{ github.ref }}#${{ github.sha }}