name: Image Build
on: [push]
jobs:
  checkout:
    name: Checkout Repository
    runs-on: ubuntu-latest
    steps:
        - name: Check out the repo
          uses: actions/checkout@v3
        - name: Debug
          run: |
            pwd
            ls -alt
        - uses: actions/download-artifact@master
          with:
            name: repo
            path: /home/runner/work/auto-provider-id/auto-provider-id
  build_image:
    name: Build Image
    runs-on: ubuntu-latest
    container:
        image: gcr.io/kaniko-project/executor:debug
    steps:
        - uses: actions/download-artifact@master
          with:
            name: repo
            path: /home/runner/work/auto-provider-id/auto-provider-id
        - name: Build the image
          run: |
            mkdir -p /kaniko/.docker
            echo "{\"auths\":{\"gchr.io\":{\"username\":\"${{ github.actor }}\",\"password\":\"${{ secrets.GITHUB_TOKEN }}\"}}}" > /kaniko/.docker/config.json
            /kaniko/executor --destination  gchr.io/${{ github.actor }}/auto-provider-id